#!/bin/bash
# . bash_aliases
alias e='/home/ejdnew/.vim/bundle/vim-erlang-tags/bin/vim-erlang-tags.erl' 
alias v='vi ~/.vimrc'
alias 1.='cd ..'
alias 2.='cd ../..'
alias 3.='cd ../../..'
alias 4.='cd ../../../..'
alias 5.='cd ../../../../..'
alias 6.='cd ../../../../../..'
alias 7.='cd ../../../../../../..'
alias 8.='cd ../../../../../../../..'
alias 9.='cd ../../../../../../../../..'
alias a='/usr/bin/vim ~/.bashrc && source ~/.bashrc && echo "Sourced ~/.bashrc"'
alias aa='source ~/.bashrc && echo "Sourced ~/.bashrc"'
alias b='/usr/bin/vim ~/.bash_profile && source ~/.bash_profile && echo "Sourced /.bash_profile"'
alias bb='source ~/.bashprofile && echo "Sourced ~/.bashprofile"'
alias c='cd '
alias d='ls -latr | grep "^d"'
alias d10='du -cks *|sort -rn|head -11'
alias diff='colordiff'
alias dldir="wget -c -nd -r -l 0 -np"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias f='open -a Finder ./'
alias file='/usr/bin/file'
alias flushd="dscacheutil -flushcache"
alias grep='grep --color=auto'
alias h='history'
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
#alias ip='curl ip.appspot.com'
alias ipext='curl ifconfig.me'
alias jpp="python -mjson.tool"
alias l='ls -latrhFG'
alias lp='lp -o sides=two-sided-long-edge -o cpi=14 -o page-left=36 -o page-right=36'
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'''
alias ls='ls -FG'
alias n='date +"%T"'
alias nl='lsof -i -P | grep LISTEN'
alias oc='open -a Google\ Chrome'
alias p='echo -e ${PATH//:/\\n}'
alias q='exit'
alias root='sudo -i'
alias tf='tail -f'
alias tm='vim ~/.tmux.conf'
alias tma='tmux attach || tmux'
alias topy='tmux attach -t topy || tmux new-session -s topy -d "htop" \; rename-window htop \; split-window -v -p 15 "iotop -o" \; attach -t topy'
alias tmn='tmux new -s $1 '
alias tmat='tmux a -t $1'
alias tl="tmux list-sessions"
alias vi='/usr/bin/vim '
#alias v='/usr/bin/vim '
alias vii='/usr/bin/vim '
alias wget='wget -c'
alias y='/usr/bin/vim ~/.bashaliases && source ~/.bashaliases && echo "Sourced ~/.bashaliases"'
alias yy='source ~/.bashaliases && echo "Sourced ~/.bashaliases"'
alias z='/usr/bin/vim ~/.git_stuff && source ~/.git_stuff && echo "Sourced ~/.git_stuff"'
alias zz='source ~/.gitstuff && echo "Sourced ~/.gitstuff"'



