#!/bin/bash

mkdir -p ~/.dots.bak
mv ~/.bash_profile ~/.dots.bak/.bash_profile
mv ~/.bashrc ~/.dots.bak/.bashrc
mv ~/.bashaliases ~/.dots.bak/.bashaliases
mv ~/.git_stuff ~/.dots.bak/.git_stuff
mv ~/.vim ~/.dots.bak/.vim
mv ~/.vimrc ~/.dots.bak/.vimrc
mv ~/.tmux.conf ~/.dots.bak/.tmux.conf
mv ~/.gitconfig ~/.dots.bak/.gitconfig
mv ~/.netrc ~/.dots.bak/.netrc

ln -s ~/sandbox/dots/.bash_profile ~/.bash_profile
ln -s ~/sandbox/dots/.bashrc ~/.bashrc
ln -s ~/sandbox/dots/.bashaliases ~/.bashaliases
ln -s ~/sandbox/dots/.git_stuff ~/.git_stuff
ln -s ~/sandbox/dots/.vim ~/.vim
ln -s ~/sandbox/dots/.vimrc ~/.vimrc
ln -s ~/sandbox/dots/.tmux.conf ~/.tmux.conf
ln -s ~/sandbox/dots/.gitconfig ~/.gitconfig
ln -s ~/sandbox/.netrc ~/.netrc

