#!/bin/bash

mv ~/.bash_profile ~/.bash_profile.bak
mv ~/.bashrc ~/.bashrc.bak
mv ~/.bashaliases ~/.bashaliases.bak
mv ~/.git_stuff ~/.git_stuff.bak
mv ~/.vim ~/.vim.bak
mv ~/.vimrc ~/.vimrc.bak
mv ~/.tmux.conf ~/.tmux.conf.bak
mv ~/.gitconfig ~/.gitconfig.bak

ln -s ~/dots/.bash_profile ~/.bash_profile
ln -s ~/dots/.bashrc ~/.bashrc
ln -s ~/dots/.bashaliases ~/.bashaliases
ln -s ~/dots/.git_stuff ~/.git_stuff
ln -s ~/dots/.vim ~/.vim
ln -s ~/dots/.vimrc ~/.vimrc
ln -s ~/dots/.tmux.conf ~/.tmux.conf
ln -s ~/dots/.gitconfig ~/.gitconfig

